# These are supported funding model platforms

patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
