# These are supported funding model platforms

patreon: # Replace with a single Patreon username
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
